STAT_COEFFS = {
    "FTM": 0.5,
    "FG3M": 1,
    "PTS": 1,
    "REB": 1.2,
    "AST": 1.5,
    "STL": 3,
    "BLK": 3,
    "TOV": -1,
}

SEASON_WEIGHTS = [5, 3, 2]

CURRENT_SEASON_NUM_GAMES = 72
CURRENT_SEASON_NUM_TEAMS = 30
TSA_REQUIREMENT_NORMAL_SEASON = 200
